name: Hello world
on: workflow_dispatch
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
     - name: Print hello world
       run: echo " this is build job"
  test:
   runs-on: ubuntu-latest
   steps:
     - name: Print hello world
       run: echo " this is test job"
  deploy:
   runs-on: ubuntu-latest
   steps:
     - name: Print hello world
       run: echo " this is deploy job"
